image: adoptopenjdk:11.0.10_9-jdk-openj9-0.24.0
variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dmaven.artifact.threads=50"
cache:
  paths:
    - .m2/repository/
build:
  stage: build
  script:
    - mvn clean install

deploy:
  stage: deploy
  script:
    - echo What's up yall!!"